// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoppingCartNetCore
{
    public partial class Product
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal ListPrice { get; set; }
        public decimal PurchasePrice { get; set; }
        public int MinStock { get; set; }
        public int MaxStock { get; set; }
        public int? SupplierId { get; set; }
        public int? CategoryId { get; set; }
        public int? MarkId { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public decimal? Weight { get; set; }
        public string Color { get; set; }
        public string Picture { get; set; }
        public bool Enabled { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual Category Category { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}